### ISSUE TITLE
config error?

### ISSUE THREAD

**Issue by llldar** [milkice233/efb-qq-slave#2]
When launching efb:
It says:
yaml.scanner.ScannerError: mapping values are not allowed here
  in "/root/.ehforwarderbot/profiles/default/milkice.qq/config.yaml", line 4, column 29

I copied your config but it doesn't work, I got wechat working but not this one.

**Comment by milkice233** [comment]
Hello,
It seems that yaml scanner fails to parse your config file. Please post your config here so that we can help solve the issue. Meanwhile, please delete some sensitive contents(Access Token, for example) before posting.

**Comment by llldar** [comment]
my config look like this:

```yaml
Client: CoolQ                         
CoolQ:
   type: HTTP                        
   access_token: 613aa25a30bb2081ccdb5b1eb8e50c30
   api_root: http://127.0.0.1:4567/  
   host: 127.0.0.1                   
   port: 1234
   is_pro: flase                      
   air_option:                       
       upload_to_smms: true          

```

access token is a randomly generated 32bit hex number(not the one I'm using)

api root and port was changed accordingly with my docker params.
